A plain build doesn't run the ppx or link the runtime.

  $ DUNE_CACHE=disabled dune build --root . 2>&1
  $ test -d _build/assay || echo "no .muts files"
  no .muts files

A full run. The library's mutants run against both targets that link it; the
executable's run against the executable, recorded under exe.bin. There are two
tests called check; the target's command says which one it means (a wrong
guess would print a warning and fail every mutant).

  $ assay 2>err.txt
  operator    generated   killed  survived   hung  error  skipped
  extreme             2        2         0      0      0        0
  sbr                 4        2         2      0      0        0
  ror                 4        2         2      0      0        0
  lcr                 1        0         1      0      0        0
  aor                 1        1         0      0      0        0
  uoi                 3        3         0      0      0        0
  empty               0        0         0      0      0        0
  total              15       10         5      0      0        0
  
  killed by
        7  main (main)
        2  check (labels)
        1  check (low)
  
  survived
    || -> &&                           bin/main.ml:4
    if c then e -> ()                  bin/main.ml:4
    e1; e2 -> e2                       bin/main.ml:6
    < -> <=                            lib/calc.ml:1
    > -> >=                            lib/calc.ml:1
  
  one line per mutant in assay.results, a record per file in assay.records
  $ grep -v 's  \|elapsed\|^building' err.txt
  running baseline (no mutant)
  querying dune for target dependencies
  $ ls _build/assay
  calc.muts
  exe.bin.muts
  $ sed 's/on [0-9-]* -*/on DATE/' assay.records
  (* -- mutation testing, generated by assay on DATE
        bin/main.ml, 8 mutants, 5 killed, 3 survived.
          extreme      1  all killed, (main) 1
          sbr          2  0 killed; 2 survived
          ror          2  all killed, (main) 2
          lcr          1  0 killed; 1 survived
          aor          1  all killed, (main) 1
          uoi          1  all killed, (main) 1
        survived at lines 4 6
     ---------------------------------------------------------------------- *)
  
  (* -- mutation testing, generated by assay on DATE
        lib/calc.ml, 7 mutants, 5 killed, 2 survived.
          extreme      1  all killed, (main) 1
          sbr          2  all killed, (labels) 2
          ror          2  0 killed; 2 survived
          uoi          2  all killed, check (low): 1, main (main): 1
        survived at lines 1
     ---------------------------------------------------------------------- *)
  

Skip a point, giving a reason, and rebuild from clean.

  $ awk -F'\t' '$6 == "double -> 0" {print $1 "\tjust testing"}' _build/assay/exe.bin.muts > assay.skip
  $ dune clean --root .
  $ assay 2>/dev/null | sed -n '/^extreme/p;/^total/p;/skipped, by reason/,/^$/p'
  extreme             2        1         0      0      0        1
  total              15        9         5      0      0        1
  skipped, by reason
        1  just testing
  
  $ grep -c skipped _build/assay/exe.bin.muts
  1

The report can be regenerated from the results file without running anything.

  $ assay -from assay.results -records again.records | sed -n '/^total/p'
  total              15        9         5      0      0        1
