bin/dune passes the skip list to the ppx with -skip and lists it in deps,
so the file has to exist.

  $ touch assay.skip

A plain build doesn't run the ppx or link the runtime.

  $ DUNE_CACHE=disabled dune build --root . 2>&1
  $ test -d _build/assay || echo "no .muts files"
  no .muts files

A full run. The library's mutants run against both targets that link it; the
executable's run against the executable, recorded under exe.bin. There are two
tests called check; the target's command says which one it means (a wrong
guess would print a warning and fail every mutant).

  $ assay 2>err.txt
  operator    generated   killed  survived   hung  error  skipped
  extreme             3        3         0      0      0        0
  sbr                12        7         4      0      0        1
  ror                 5        3         2      0      0        0
  lcr                 1        0         1      0      0        0
  aor                 1        1         0      0      0        0
  uoi                 4        4         0      0      0        0
  empty               0        0         0      0      0        0
  total              26       18         7      0      0        1
  
  skipped, by reason
        1  doesn't type-check: This expression has type int list -> string list
  
  killed by
       15  main (main)
        2  check (labels)
        1  check (low)
  
  survived
    || -> &&                           bin/main.ml:4
    if c then e -> ()                  bin/main.ml:4
    e1; e2 -> e2                       bin/main.ml:6
    if c then e -> ()                  bin/main.ml:14
    e1; e2 -> e2                       bin/main.ml:16
    < -> <=                            lib/calc.ml:1
    > -> >=                            lib/calc.ml:1
  
  one line per mutant in assay.results, a record per file in assay.records
Dropping the last stage of shown's pipeline doesn't type-check. The error
starts at that point, so assay adds it to the skip list and builds again.

  $ grep -v 's  \|elapsed\|^building' err.txt
    skipping e |> f -> e at bin/main.ml:11
  added 1 point to assay.skip that doesn't type-check
  running baseline (no mutant)
  querying dune for target dependencies
  $ ls _build/assay
  calc.muts
  exe.bin.muts
  $ sed 's/on [0-9-]* -*/on DATE/' assay.records
  (* -- mutation testing, generated by assay on DATE
        bin/main.ml, 18 mutants, 13 killed, 5 survived.
          extreme      2  all killed, (main) 2
          sbr          9  5 killed, (main) 5; 4 survived
          ror          3  all killed, (main) 3
          lcr          1  0 killed; 1 survived
          aor          1  all killed, (main) 1
          uoi          2  all killed, (main) 2
        survived in let () (sbr 2, lcr), let ()#2 (sbr 2)
     ---------------------------------------------------------------------- *)
  
  (* -- mutation testing, generated by assay on DATE
        lib/calc.ml, 7 mutants, 5 killed, 2 survived.
          extreme      1  all killed, (main) 1
          sbr          2  all killed, (labels) 2
          ror          2  0 killed; 2 survived
          uoi          2  all killed, check (low): 1, main (main): 1
        survived in clamp (ror 2)
     ---------------------------------------------------------------------- *)
  

Skip a point, giving a reason, and rebuild from clean.

  $ awk -F'\t' '$7 == "double -> 0" {print $1 "\tjust testing"}' _build/assay/exe.bin.muts > assay.skip
  $ dune clean --root .
  $ assay 2>/dev/null | sed -n '/^extreme/p;/^total/p;/skipped, by reason/,/^$/p'
  extreme             3        2         0      0      0        1
  total              26       17         7      0      0        2
  skipped, by reason
        1  doesn't type-check: This expression has type int list -> string list
        1  just testing
  
  $ grep -c skipped _build/assay/exe.bin.muts
  2

The report can be regenerated from the results file without running anything.

  $ assay -from assay.results -records again.records | sed -n '/^total/p'
  total              26       17         7      0      0        2

A skip-list entry whose point has gone (usually because the code above it
moved) skips nothing, and says so. So does one added without a clean build,
since dune reuses the preprocessing from before.

  $ printf '12345\tgone now\n' >> assay.skip
  $ awk -F'\t' '$7 == "< -> <=" {print $1 "\tnot rebuilt"}' _build/assay/calc.muts >> assay.skip
  $ assay 2>&1 >/dev/null | grep -v 's  \|elapsed\|^building\|^running\|^querying' | sed 's/^  [0-9]*  /  ID  /'
  warning: these entries in assay.skip match no mutation point, so they skip nothing. The code they were for has changed or gone; remove them, or find the points again and update the ids.
    ID  gone now
  warning: these entries in assay.skip weren't applied, so their mutants will run. dune reused older preprocessing because it doesn't know the skip list is an input. Pass it to the ppx with -skip and list it in deps (see the README), or run dune clean and build again.
    ID  lib/calc.ml:1  < -> <=  not rebuilt

Results are written as mutants finish, so an interrupted run leaves a partial
file. It's marked, and -from says so.

  $ (echo '# unfinished run: 15 mutants.'; grep -v skipped assay.results | head -3) > partial.results
  $ assay -from partial.results -records /dev/null 2>&1 | sed -n '/^warning/p;/^total/p'
  warning: partial.results is from a run that didn't finish. It has results for 3 of 15 mutants.
  total               3        1         2      0      0        0
  $ cat assay.skip
  2182414739768454223	just testing
  4240568672125944075	doesn't type-check: This expression has type int list -> string list
  12345	gone now
  1001076084413183600	not rebuilt

Ids come from what a point is, not where it is, so lines added above the
points leave every id (and so every skip) as it was.

  $ cut -f1,7,8 _build/assay/exe.bin.muts | grep -v '^#' | sort > before
  $ (printf '(* A comment,\n   and a blank line. *)\n\n'; cat bin/main.ml) > moved.ml && mv moved.ml bin/main.ml
  $ ASSAY_MUTS_DIR=$PWD/_build/assay DUNE_CACHE=disabled dune build --root . --instrument-with assay 2>&1
  $ cut -f1,7,8 _build/assay/exe.bin.muts | grep -v '^#' | sort | diff before - && echo same ids
  same ids

Changing the pipeline's code changes its id. The entry assay added for the old
code is removed and one for the new code is added. An [@assay.skip] attribute
skips every point inside it, with its reason.

  $ perl -pi -e 's/xs \|> List.rev \|>/(xs |> List.rev [\@assay.skip "the order is checked elsewhere"]) |>/' bin/main.ml
  $ grep 'assay.skip' bin/main.ml
  let shown (xs : int list) : string list = (xs |> List.rev [@assay.skip "the order is checked elsewhere"]) |> List.map string_of_int
  $ assay 2>&1 | grep '^removed\|^  skipping\|^added\|^warning'
    skipping e |> f -> e at bin/main.ml:14
  added 1 point to assay.skip that doesn't type-check
  removed 1 entry from assay.skip that no longer matches a point
  warning: these entries in assay.skip match no mutation point, so they skip nothing. The code they were for has changed or gone; remove them, or find the points again and update the ids.
  warning: these entries in assay.skip weren't applied, so their mutants will run. dune reused older preprocessing because it doesn't know the skip list is an input. Pass it to the ppx with -skip and list it in deps (see the README), or run dune clean and build again.
  $ assay -from assay.results 2>/dev/null | sed -n '/skipped, by reason/,/^$/p'
  skipped, by reason
        1  doesn't type-check: This expression has type int list -> string list
        1  just testing
        1  the order is checked elsewhere
  

Records live in the tests, and -check-records compares them with a run. Here
the block for lib/calc.ml is out of date (and has an old date, which alone
wouldn't count), lib/gone.ml has no mutants any more, and bin/main.ml's block
hasn't been placed anywhere.

  $ mkdir laws
  $ (awk -v RS= '/lib\/calc.ml,/' assay.records | sed 's/ror 2/ror 1/; s/on [0-9-]* /on 2001-01-01 /'; echo; echo 'let () = ()') > laws/law_calc.ml
  $ cat > laws/law_gone.ml <<'END'
  > (* -- mutation testing, generated by assay on 2001-01-01 ---------------------
  >       lib/gone.ml, 1 mutants, 1 killed.
  >    ---------------------------------------------------------------------- *)
  > 
  > let () = ()
  > END
  $ assay -from assay.results -check-records laws > out 2>/dev/null
  [1]
  $ sed -n '/^records/,$p' out
  records in laws:
    out of date lib/calc.ml in laws/law_calc.ml
    orphaned    lib/gone.ml from laws/law_gone.ml (it has no mutants now)
    no home     bin/main.ml (most kills by main)
    0 up to date

-update-records rewrites the out-of-date block and removes the orphaned one
(with the blank line after it). Blocks with no home are left to place by hand.

  $ assay -from assay.results -update-records laws 2>/dev/null | sed -n '/^records/,$p'
  records in laws:
    updated     lib/calc.ml in laws/law_calc.ml
    removed     lib/gone.ml from laws/law_gone.ml (it has no mutants now)
    no home     bin/main.ml (most kills by main)
    0 up to date; place the ones with no home by hand, and the next run will keep them
  $ sed 's/on [0-9-]* -*/on DATE/' laws/law_calc.ml
  (* -- mutation testing, generated by assay on DATE
        lib/calc.ml, 7 mutants, 5 killed, 2 survived.
          extreme      1  all killed, (main) 1
          sbr          2  all killed, (labels) 2
          ror          2  0 killed; 2 survived
          uoi          2  all killed, check (low): 1, main (main): 1
        survived in clamp (ror 2)
     ---------------------------------------------------------------------- *)
  
  let () = ()
  $ cat laws/law_gone.ml
  let () = ()

Once bin/main.ml's block is placed, everything is up to date.

  $ awk -v RS= '/bin\/main.ml,/' assay.records > laws/main.ml
  $ assay -from assay.results -check-records laws 2>/dev/null | sed -n '/^records/,$p'
  records in laws:
    2 up to date

A run limited with -only (recorded in the results file) doesn't know about
other libraries, so it never calls their blocks orphaned.

  $ cp laws/law_calc.ml laws/law_gone.ml
  $ sed -i.bak 's/lib\/calc.ml/lib\/gone.ml/' laws/law_gone.ml
  $ (echo '# only: exe.bin'; cat assay.results) > limited.results
  $ assay -from limited.results -check-records laws 2>/dev/null | sed -n '/^records/,$p'
  records in laws:
    not in run  lib/gone.ml in laws/law_gone.ml
    2 up to date

With -check-records or -update-records, -from leaves assay.records alone: the
run that made the results already wrote it. -records still asks for it.

  $ echo 'not rewritten' > assay.records
  $ assay -from assay.results -check-records laws > /dev/null 2>&1
  [1]
  $ assay -from assay.results -update-records laws > /dev/null 2>&1
  $ cat assay.records
  not rewritten
  $ assay -from assay.results -check-records laws -records assay.records > /dev/null 2>&1
  $ grep -c 'mutation testing' assay.records
  2
