open StdLabels

type report =
  { stale : (string * string) list
  ; orphaned : (string * string) list
  ; homeless : string list
  ; outside : (string * string) list
  ; current : int
  }

(* A block in a test: where it is (0-based line indices, inclusive), which
   source it's for, and its lines. *)
type found =
  { first : int
  ; last : int
  ; source : string
  ; lines : string list
  }

let marker = "(* -- mutation testing, generated by assay on"

let starts_with ~(prefix : string) (s : string) : bool =
  String.length s >= String.length prefix
  && String.equal (String.sub s ~pos:0 ~len:(String.length prefix)) prefix
;;

let ends_with ~(suffix : string) (s : string) : bool =
  let n = String.length s
  and k = String.length suffix in
  n >= k && String.equal (String.sub s ~pos:(n - k) ~len:k) suffix
;;

(* The source file named on a block's second line, e.g. [lib/x.ml] from
   [      lib/x.ml, 25 mutants, 23 killed, 2 survived.]. *)
let source_of (line : string) : string option =
  let line = String.trim line in
  let rec find (from : int) : int option =
    match String.index_from_opt line from ',' with
    | None -> None
    | Some i ->
      let rest = String.sub line ~pos:(i + 1) ~len:(String.length line - i - 1) in
      (match Scanf.sscanf_opt rest " %d mutant%s" (fun _ _ -> ()) with
       | Some () -> Some i
       | None -> find (i + 1))
  in
  Option.map (fun i -> String.sub line ~pos:0 ~len:i) (find 0)
;;

let is_end (line : string) : bool =
  let line = String.trim line in
  starts_with ~prefix:"-" line && ends_with ~suffix:"*)" line
;;

let blocks_in (lines : string array) : found list =
  let n = Array.length lines in
  let rec go (i : int) (found : found list) : found list =
    if i >= n
    then List.rev found
    else if not (starts_with ~prefix:marker (String.trim lines.(i)))
    then go (i + 1) found
    else (
      let rec close (j : int) : int option =
        if j >= n
        then None
        else if is_end lines.(j)
        then Some j
        else if starts_with ~prefix:marker (String.trim lines.(j))
        then None
        else close (j + 1)
      in
      match close (i + 1), if i + 1 < n then source_of lines.(i + 1) else None with
      | Some last, Some source ->
        let lines = Array.to_list (Array.sub lines ~pos:i ~len:(last - i + 1)) in
        go (last + 1) ({ first = i; last; source; lines } :: found)
      | _, _ -> go (i + 1) found)
  in
  go 0 []
;;

let rec tests (dir : string) : string list =
  let entries =
    try List.sort ~cmp:String.compare (Array.to_list (Sys.readdir dir)) with
    | Sys_error _ -> []
  in
  List.concat_map entries ~f:(fun name ->
    let path = Filename.concat dir name in
    if String.length name > 0 && (name.[0] = '_' || name.[0] = '.')
    then []
    else if Sys.is_directory path
    then tests path
    else if Filename.check_suffix name ".ml" || Filename.check_suffix name ".mli"
    then [ path ]
    else [])
;;

let test_named ~(dir : string) (name : string) : string option =
  List.find_opt (tests dir) ~f:(fun path ->
    String.equal (Filename.basename path) (name ^ ".ml"))
;;

(* The block's lines, indented like the one it replaces. The first line
   only carries the date, so it's left out when comparing. *)
let indented (indent : string) (block : string) : string list =
  List.filter_map (String.split_on_char ~sep:'\n' block) ~f:(fun line ->
    if String.length line = 0 then None else Some (indent ^ line))
;;

let same (old_lines : string list) (new_lines : string list) : bool =
  match old_lines, new_lines with
  | _ :: a, _ :: b -> List.equal ~eq:String.equal a b
  | _, _ -> false
;;

let indent_of (line : string) : string =
  let n = String.length line in
  let rec go (i : int) : int = if i < n && line.[i] = ' ' then go (i + 1) else i in
  String.sub line ~pos:0 ~len:(go 0)
;;

let run
      ~(write : bool)
      ~(dir : string)
      ~(blocks : (string * string) list)
      ~(complete : bool)
  : report
  =
  let stale = ref []
  and orphaned = ref []
  and outside = ref []
  and current = ref 0
  and placed = Hashtbl.create 64 in
  List.iter (tests dir) ~f:(fun test ->
    let text = Files.read test in
    let lines = Array.of_list (String.split_on_char ~sep:'\n' text) in
    let found = blocks_in lines in
    (* What to put in place of each block: [Some lines], or [None] to drop
       it. Blocks not mentioned stay as they are. *)
    let changes =
      List.filter_map found ~f:(fun (b : found) ->
        Hashtbl.replace placed b.source ();
        match List.assoc_opt b.source blocks with
        | Some block ->
          let replacement = indented (indent_of (List.hd b.lines)) block in
          if same b.lines replacement
          then (
            incr current;
            None)
          else (
            stale := (test, b.source) :: !stale;
            Some (b, Some replacement))
        | None when complete ->
          orphaned := (test, b.source) :: !orphaned;
          Some (b, None)
        | None ->
          outside := (test, b.source) :: !outside;
          None)
    in
    if write && changes <> []
    then (
      let n = Array.length lines in
      let out = Buffer.create (String.length text) in
      let emit (line : string) (i : int) : unit =
        Buffer.add_string out line;
        if i < n - 1 then Buffer.add_char out '\n'
      in
      let rec go (i : int) : unit =
        if i < n
        then (
          match List.find_opt changes ~f:(fun ((b : found), _) -> b.first = i) with
          | Some (b, Some replacement) ->
            List.iter replacement ~f:(fun line ->
              Buffer.add_string out line;
              Buffer.add_char out '\n');
            go (b.last + 1)
          | Some (b, None) ->
            (* Take the blank line after it too, so no gap is left. *)
            let next = b.last + 1 in
            go
              (if next < n - 1 && String.length (String.trim lines.(next)) = 0
               then next + 1
               else next)
          | None ->
            emit lines.(i) i;
            go (i + 1))
      in
      go 0;
      let oc = open_out_bin test in
      Fun.protect
        ~finally:(fun () -> close_out oc)
        (fun () -> output_string oc (Buffer.contents out))));
  { stale = List.rev !stale
  ; orphaned = List.rev !orphaned
  ; homeless =
      List.filter_map blocks ~f:(fun (source, _) ->
        if Hashtbl.mem placed source then None else Some source)
  ; outside = List.rev !outside
  ; current = !current
  }
;;

let check = run ~write:false
let update = run ~write:true
