open StdLabels

(* Summary of what killed the mutants, e.g. [(g) 5 (b) 2]. If more than one
   target was involved, include the target names: [law_layout (g): 5,
   law_fuzz (b): 2]. *)
let killers (rows : (Points.t * Run.outcome) list) : string =
  let named =
    List.filter_map rows ~f:(fun (_, outcome) ->
      match outcome with
      | Run.Killed { target; part } -> Some (target, part)
      | Run.Survived | Run.Hung _ | Run.Errored _ -> None)
  in
  (* If we couldn't parse a part (e.g. expect tests, which just print a
     diff), show the target name alone rather than "target ?". *)
  let named =
    List.map named ~f:(fun (target, part) ->
      target, if String.equal part "?" then "" else part)
  in
  let join (target : string) (part : string) : string =
    if String.length part = 0 then target else target ^ " " ^ part
  in
  let targets = List.sort_uniq ~cmp:String.compare (List.map named ~f:fst) in
  match targets with
  | [ _ ] when List.for_all named ~f:(fun (_, part) -> String.length part > 0) ->
    String.concat
      ~sep:" "
      (List.map
         (Summary.tally (List.map named ~f:snd))
         ~f:(fun (part, n) -> Printf.sprintf "%s %d" part n))
  | _ ->
    String.concat
      ~sep:", "
      (List.map
         (Summary.tally (List.map named ~f:(fun (target, part) -> join target part)))
         (* Colon before the count so it doesn't look like part of the name. *)
         ~f:(fun (who, n) -> Printf.sprintf "%s: %d" who n))
;;

let block ~(today : string) (file : string) (rows : (Points.t * Run.outcome) list)
  : string
  =
  let buf = Buffer.create 1024 in
  let total = List.length rows in
  let k = Summary.count rows ~f:Summary.is_killed in
  let s = Summary.count rows ~f:Summary.is_survived in
  let h = Summary.count rows ~f:Summary.is_hung in
  let e = Summary.count rows ~f:Summary.is_errored in
  let tail =
    (if s = 0 then "" else Printf.sprintf ", %d survived" s)
    ^ (if h = 0 then "" else Printf.sprintf ", %d timed out" h)
    ^ if e = 0 then "" else Printf.sprintf ", %d could not be run" e
  in
  Buffer.add_string
    buf
    (Printf.sprintf
       "(* -- mutation testing, generated by assay on %s %s\n"
       today
       (String.make (max 3 (31 - String.length today)) '-'));
  Buffer.add_string
    buf
    (Printf.sprintf "      %s, %d mutants, %d killed%s.\n" file total k tail);
  let operators =
    List.sort
      ~cmp:(fun a b -> compare (Summary.rank a) (Summary.rank b))
      (List.sort_uniq
         ~cmp:String.compare
         (List.map rows ~f:(fun ((p : Points.t), _) -> p.operator)))
  in
  List.iter operators ~f:(fun operator ->
    let mine =
      List.filter rows ~f:(fun ((p : Points.t), _) -> String.equal p.operator operator)
    in
    let n = List.length mine in
    let k = Summary.count mine ~f:Summary.is_killed in
    let s = Summary.count mine ~f:Summary.is_survived in
    let h = Summary.count mine ~f:Summary.is_hung in
    let e = Summary.count mine ~f:Summary.is_errored in
    let verdict = if k = n then "all killed" else Printf.sprintf "%d killed" k in
    let rest =
      (if s = 0 then "" else Printf.sprintf "; %d survived" s)
      ^ (if h = 0 then "" else Printf.sprintf "; %d timed out" h)
      ^ if e = 0 then "" else Printf.sprintf "; %d could not be run" e
    in
    let by = killers mine in
    Buffer.add_string
      buf
      (Printf.sprintf
         "        %-10s %3d  %s%s%s\n"
         operator
         n
         verdict
         (if String.length by = 0 then "" else ", " ^ by)
         rest));
  (* List survivor line numbers so there's somewhere to start looking. *)
  let lines =
    List.sort_uniq
      ~cmp:compare
      (List.filter_map rows ~f:(fun ((p : Points.t), outcome) ->
         if Summary.is_survived outcome then Some p.line else None))
  in
  if lines <> []
  then (
    Buffer.add_string buf "      survived at lines";
    List.iter lines ~f:(fun line -> Buffer.add_string buf (Printf.sprintf " %d" line));
    Buffer.add_char buf '\n');
  Buffer.add_string buf "   ";
  Buffer.add_string buf (String.make 70 '-');
  Buffer.add_string buf " *)\n";
  Buffer.contents buf
;;

let write ~(path : string) ~(today : string) (outcomes : (Points.t * Run.outcome) list)
  : unit
  =
  let by_file = Hashtbl.create 64 in
  List.iter outcomes ~f:(fun (((p : Points.t), _) as row) ->
    Hashtbl.replace
      by_file
      p.file
      (row :: Option.value (Hashtbl.find_opt by_file p.file) ~default:[]));
  let files =
    List.sort
      ~cmp:(fun (a, x) (b, y) ->
        let sa = Summary.count x ~f:Summary.is_survived
        and sb = Summary.count y ~f:Summary.is_survived in
        if sa = sb then String.compare a b else compare sb sa)
      (Hashtbl.fold (fun file rows acc -> (file, List.rev rows) :: acc) by_file [])
  in
  let oc = open_out path in
  Fun.protect
    ~finally:(fun () -> close_out oc)
    (fun () ->
       List.iter files ~f:(fun (file, rows) ->
         output_string oc (block ~today file rows);
         output_char oc '\n'))
;;
