open StdLabels

(* Summary of what killed the mutants, e.g. [(g) 5 (b) 2]. If more than one
   target was involved, include the target names: [law_layout (g): 5,
   law_fuzz (b): 2]. *)
let killers (rows : (Points.t * Run.outcome) list) : string =
  let named =
    List.filter_map rows ~f:(fun (_, outcome) ->
      match outcome with
      | Run.Killed { target; part } -> Some (target, part)
      | Run.Survived | Run.Hung _ | Run.Errored _ -> None)
  in
  (* If we couldn't parse a part (e.g. expect tests, which just print a
     diff), show the target name alone rather than "target ?". *)
  let named =
    List.map named ~f:(fun (target, part) ->
      target, if String.equal part "?" then "" else part)
  in
  let join (target : string) (part : string) : string =
    if String.length part = 0 then target else target ^ " " ^ part
  in
  let targets = List.sort_uniq ~cmp:String.compare (List.map named ~f:fst) in
  match targets with
  | [ _ ] when List.for_all named ~f:(fun (_, part) -> String.length part > 0) ->
    String.concat
      ~sep:" "
      (List.map
         (Summary.tally (List.map named ~f:snd))
         ~f:(fun (part, n) -> Printf.sprintf "%s %d" part n))
  | _ ->
    String.concat
      ~sep:", "
      (List.map
         (Summary.tally (List.map named ~f:(fun (target, part) -> join target part)))
         (* Colon before the count so it doesn't look like part of the name. *)
         ~f:(fun (who, n) -> Printf.sprintf "%s: %d" who n))
;;

let block ~(today : string) (file : string) (rows : (Points.t * Run.outcome) list)
  : string
  =
  let buf = Buffer.create 1024 in
  let total = List.length rows in
  let k = Summary.count rows ~f:Summary.is_killed in
  let s = Summary.count rows ~f:Summary.is_survived in
  let h = Summary.count rows ~f:Summary.is_hung in
  let e = Summary.count rows ~f:Summary.is_errored in
  let tail =
    (if s = 0 then "" else Printf.sprintf ", %d survived" s)
    ^ (if h = 0 then "" else Printf.sprintf ", %d timed out" h)
    ^ if e = 0 then "" else Printf.sprintf ", %d could not be run" e
  in
  Buffer.add_string
    buf
    (Printf.sprintf
       "(* -- mutation testing, generated by assay on %s %s\n"
       today
       (String.make (max 3 (31 - String.length today)) '-'));
  Buffer.add_string
    buf
    (Printf.sprintf "      %s, %d mutants, %d killed%s.\n" file total k tail);
  let operators =
    List.sort
      ~cmp:(fun a b -> compare (Summary.rank a) (Summary.rank b))
      (List.sort_uniq
         ~cmp:String.compare
         (List.map rows ~f:(fun ((p : Points.t), _) -> p.operator)))
  in
  List.iter operators ~f:(fun operator ->
    let mine =
      List.filter rows ~f:(fun ((p : Points.t), _) -> String.equal p.operator operator)
    in
    let n = List.length mine in
    let k = Summary.count mine ~f:Summary.is_killed in
    let s = Summary.count mine ~f:Summary.is_survived in
    let h = Summary.count mine ~f:Summary.is_hung in
    let e = Summary.count mine ~f:Summary.is_errored in
    let verdict = if k = n then "all killed" else Printf.sprintf "%d killed" k in
    let rest =
      (if s = 0 then "" else Printf.sprintf "; %d survived" s)
      ^ (if h = 0 then "" else Printf.sprintf "; %d timed out" h)
      ^ if e = 0 then "" else Printf.sprintf "; %d could not be run" e
    in
    let by = killers mine in
    Buffer.add_string
      buf
      (Printf.sprintf
         "        %-10s %3d  %s%s%s\n"
         operator
         n
         verdict
         (if String.length by = 0 then "" else ", " ^ by)
         rest));
  (* Name survivors by binding and operator, which stay true when code above
     them moves. Results from before bindings were recorded fall back to line
     numbers. *)
  let survivors =
    List.sort
      ~cmp:(fun ((a : Points.t), _) ((b : Points.t), _) -> compare a.line b.line)
      (List.filter rows ~f:(fun (_, outcome) -> Summary.is_survived outcome))
  in
  if survivors <> []
  then (
    let named =
      List.map survivors ~f:(fun ((p : Points.t), _) ->
        if String.length p.binding = 0
        then Printf.sprintf "line %d" p.line, p.operator
        else p.binding, p.operator)
    in
    (* In order of first appearance, each with its operators. *)
    let bindings =
      List.fold_left named ~init:[] ~f:(fun acc (binding, _) ->
        if List.mem binding ~set:acc then acc else binding :: acc)
      |> List.rev
    in
    let items =
      List.map bindings ~f:(fun binding ->
        let operators =
          List.filter_map named ~f:(fun (b, operator) ->
            if String.equal b binding then Some operator else None)
          |> List.sort ~cmp:(fun a b -> compare (Summary.rank a) (Summary.rank b))
        in
        let counted =
          List.fold_left operators ~init:[] ~f:(fun acc operator ->
            match acc with
            | (o, n) :: rest when String.equal o operator -> (o, n + 1) :: rest
            | _ -> (operator, 1) :: acc)
          |> List.rev_map ~f:(fun (operator, n) ->
            if n = 1 then operator else Printf.sprintf "%s %d" operator n)
        in
        Printf.sprintf "%s (%s)" binding (String.concat ~sep:", " counted))
    in
    (* Wrap to keep the comment within 80 columns. *)
    let width = 78 in
    let column = ref 0 in
    let add (text : string) : unit =
      Buffer.add_string buf text;
      column := !column + String.length text
    in
    add "      survived in";
    List.iteri items ~f:(fun i item ->
      let item = if i < List.length items - 1 then item ^ "," else item in
      if !column + 1 + String.length item > width && !column > 16
      then (
        Buffer.add_char buf '\n';
        column := 0;
        add "        ")
      else add " ";
      add item);
    Buffer.add_char buf '\n');
  Buffer.add_string buf "   ";
  Buffer.add_string buf (String.make 70 '-');
  Buffer.add_string buf " *)\n";
  Buffer.contents buf
;;

let blocks ~(today : string) (outcomes : (Points.t * Run.outcome) list)
  : (string * string) list
  =
  let by_file = Hashtbl.create 64 in
  List.iter outcomes ~f:(fun (((p : Points.t), _) as row) ->
    Hashtbl.replace
      by_file
      p.file
      (row :: Option.value (Hashtbl.find_opt by_file p.file) ~default:[]));
  let files =
    List.sort
      ~cmp:(fun (a, x) (b, y) ->
        let sa = Summary.count x ~f:Summary.is_survived
        and sb = Summary.count y ~f:Summary.is_survived in
        if sa = sb then String.compare a b else compare sb sa)
      (Hashtbl.fold (fun file rows acc -> (file, List.rev rows) :: acc) by_file [])
  in
  List.map files ~f:(fun (file, rows) -> file, block ~today file rows)
;;

let write ~(path : string) ~(today : string) (outcomes : (Points.t * Run.outcome) list)
  : unit
  =
  let oc = open_out path in
  Fun.protect
    ~finally:(fun () -> close_out oc)
    (fun () ->
       List.iter (blocks ~today outcomes) ~f:(fun (_, block) ->
         output_string oc block;
         output_char oc '\n'))
;;
